// Generated by LiveScript 1.5.0
//(function(){
  var ipcFile, Web3, web3, net;
  ipcFile = require('./app/config.json').ipcFile;
  Web3 = require('web3');
  net = require('net');
  web3 = new Web3;
  web3.setProvider(new web3.providers.IpcProvider(ipcFile, net));
  // 
  web3.eth.currentGasPrice = '1000000000'
  function updateCurrentGasPrice(){
    web3.eth.getGasPrice().then((price) => {
      web3.eth.currentGasPrice = price
      // console.log(price)
    });
  }
  setInterval(updateCurrentGasPrice, 15700)
  updateCurrentGasPrice()
  
  module.exports = web3;



//}).call(this);
